# Generated by Django 4.1.2 on 2022-12-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witness_name', models.CharField(max_length=255)),
                ('witness_email', models.EmailField(max_length=254)),
                ('witness_phonenumber', models.CharField(blank=True, max_length=18, null=True)),
                ('date_of_accident', models.DateField()),
                ('time_of_accident', models.TimeField()),
                ('is_fatal', models.BooleanField()),
                ('image', models.ImageField(upload_to='reports')),
                ('accident_type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('S', 'Submitted'), ('I', 'Investigation'), ('C', 'Closed')], default='S', max_length=1)),
                ('number_of_vehicles_involved', models.PositiveIntegerField()),
                ('number_of_injured_victims', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_deaths', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('type_of_road', models.CharField(max_length=255)),
                ('cause_of_accident', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Describe what happened')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
