# Generated by Django 4.1.2 on 2022-12-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_accidenttype_location_typeofroad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidenttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='typeofroad',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
