# Generated by Django 4.1.2 on 2023-01-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_accidenttype_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
